### ISSUE TITLE
How to access user's name in addition to email?

### ISSUE THREAD

**Issue by canpoyrazoglu** [Accedia/appleauth-net#14]
I'm authenticating with the scope of "name email" but I'm only getting the email in `id_token`. I've seen https://github.com/Accedia/appleauth-net/issues/7 but that issue is closed without an actual answer. It says that I can only access name data only on first request, which is fine, but doesn't tell how to access it in the first request.

If I can get the user's name only on the first request, then, how do I access user's name on the first request?

**Comment by DanailStoichkov** [comment]
You can decode the id_token and you will find the user information there. But keep in mind that it has to be the very first time this user logs into your app using Sign in with Apple. 
If you are testing this with your own account you can go to your apple id account: https://appleid.apple.com/ then go to Security > Manage apps & websites... and remove your app from the list.

**Comment by canpoyrazoglu** [comment]
This is exactly what I'm doing, and it's _not_ there.
