### ISSUE TITLE
What is private key on localhost?

### ISSUE THREAD

**Issue by martonx** [Accedia/appleauth-net#22]
Dear Contributors,

string privateKey = System.IO.File.ReadAllText("path/to/file.p8");

What is this file, how can we get this on localhost / not Azure?

**Comment by DanailStoichkov** [comment]
Hello,
This is just an example that illustrates how you can retrieve the private key file from your file system. Here you can get more info how to generate this private key: https://help.apple.com/developer-account/#/dev77c875b7e
