### ISSUE TITLE
Adjust the exp of client secret 

### ISSUE THREAD

**Issue by scottluskcis** [Accedia/appleauth-net#24]
Is it possible to make this a configurable value? It looks like in TokenGenerator class in GenerateClientSecret this is set with an exp of 5 min? 

https://github.com/Accedia/appleauth-net/blob/6d567bab4e88b92063e1ebbbde24bd978045a2f6/Cryptography/TokenGenerator.cs#L30 

I would like for a way to make this longer but not seeing this is supported. Before I fork the repo and add a change is this something anyone has already added or plan to?

**Comment by deankroker** [comment]
According to the [Apple docs](https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens), you can specify an expiration of up to 6 months—"The value must not be greater than 15777000 (6 months in seconds)"—but it appears this repository does not allow for customization of expiration time (e.g. [generation of client secret in this repo with expiration of 5 mins](https://github.com/Accedia/appleauth-net/blob/6d567bab4e88b92063e1ebbbde24bd978045a2f6/Cryptography/TokenGenerator.cs#L30)).

**Comment by DanailStoichkov** [comment]
@scottluskcis Thank you for the contribution! I have merged your PR and will release a new version in NuGet as soon as I add some more changes. Feel free to propose any other updates as well!

**Comment by scottluskcis** [comment]
Awesome, thanks for the quick response @DanailStoichkov! Great library, has been very useful. I'll look to contribute additional things in the future!

**Comment by scottluskcis** [comment]
@DanailStoichkov will a new release be pushed out that contains this change so I can update my NuGet package?

**Comment by DanailStoichkov** [comment]
@scottluskcis Not for now. We will add some other small changes before doing a release. You can just create a local nuget package and reference it for now.
