### ISSUE TITLE
Android redirect url generator

### ISSUE THREAD

**Issue by sunecko** [Accedia/appleauth-net#32]
I had to implement my own URL generator for redirect url on Android. I think it's a good idea to include this support in the library

**Comment by hectorrhg** [comment]
I had to implement my own URL generator for callbacks on Android. I think it's a good idea to include this support in the library

**Comment by sunecko** [comment]
I'm a novice in contributing to projects, but this library helps me integrate with Apple. I'm leaving a pull request [here](https://github.com/Accedia/appleauth-net/issues/32) for authentication from Android devices.
