### ISSUE TITLE
Add requestUri as an optional parameter

### ISSUE THREAD

**Issue by vzhurintulaco** [Accedia/appleauth-net#34]
Currently `requestUri` is hardcoded inside `AppleRestClient`:
- `GenerateRequestMessage` - `https://appleid.apple.com/auth/token`
- `GenerateRevokeMessage` - `https://appleid.apple.com/auth/revoke`

As a result, it is impossible to write API tests for Apple login flow using, for example, https://wiremock.org/.
Let's add at least a `baseUri` parameter with the `https://appleid.apple.com` value by default to make the experience better.

**Comment by DanailStoichkov** [comment]
A new version with different approach was just released, so now you should be able to provide the base URI and query string to the GetAuthorizationToken, GetRefreshToken and RevokeToken methods. Will close your PR.
