### ISSUE TITLE
Support .NET 4.7.2

### ISSUE THREAD

**Issue by darakis** [Accedia/appleauth-net#5]
Hello,
is it possible also to target .NET Framework? I need it for old asp.net forms project which doesn't build properly with .NET Standard 2.0. NET 4.7.1 or lower will do

**Comment by DanailStoichkov** [comment]
Hi, @darakis !
Should be no problem. I will see if that's easily achievable and will let you know as soon as I have an update.

**Comment by DanailStoichkov** [comment]
Hello, @darakis !
You can fork the repository straightaway and you can copy over the classes to a .NET Framework project and everything should be working fine.
Let me know if you are experiencing any issues with that.

**Comment by darakis** [comment]
Hello @DanailStoichkov!
This is what I've done already. I only had to change the serializer library and everything worked smoothly.
Thanks
