### ISSUE TITLE
Get FirstName and LastName of user from Apple

### ISSUE THREAD

**Issue by moathtiti** [Accedia/appleauth-net#7]
Glad to find this, I need to know how and where I can find the **First Name** and the **Last Name** _received from Apple_, 
with web API by given id_token
and if the response from apple doesn't contain such data, so **How can we get them**?

**Comment by DanailStoichkov** [comment]
Hello,
Unfortunately, you can get the FirstName and LastName only in the initial response from Apple. In the next responses you can only see the person's email.
