### ISSUE TITLE
invalid_grant error

### ISSUE THREAD

**Issue by grascioni** [Accedia/appleauth-net#9]
When calling  GetAuthorizationToken, I'm getting an error with the following message: "invalid_grant"

I'm not sure I'm providing the correct clientId to the AppleAuthProvider constructor.

Documentation comments say that it's a 10-character key identifier also known as Service ID, but I cannot find such string in the developer console. I tried several 10-character and reversed domain values, but I'm still getting that error.

Does it ring a bell to someone? Thanks!

> /// <param name="clientId">A10-character key identifier obtained from your developer account. (aka "Service ID" that is configured for “Sign In with Apple”)</param>
        /// <param name="teamId">A 10-character key identifier obtained from your developer account.</param>
        /// <param name="keyId">A 10-character key identifier obtained from your developer account. Configured for "Sign In with Apple" </param>
        /// <param name="redirectUrl">URL to which the user will be redirected after successful verification. 
        /// You need to configure a verified domain and map the redirect URL to it. Can’t be an IP address or localhost </param>
        /// <param name="state">Can be used for any internal identifiers (e.g. Session IDs, User IDs, Query Strings, etc.)</param>
        public AppleAuthProvider(string clientId, string teamId, string keyId, string redirectUrl, string state)
        {

**Comment by DanailStoichkov** [comment]
Hello,
This can be configured from your Apple Developer account.  You have to go to the "**Certificates, Identifiers & Profiles**" section and click on the blue plus icon. 
![image](https://user-images.githubusercontent.com/64973465/103893441-ff938680-50f5-11eb-91b2-46aafdabbe60.png)
Then you should select **Services IDs** from the list of identifiers.
